
const CONSTANTS = {
  EMAIL: 'EMAIL',
  LOGIN_ALREADY: '0',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  GOOGLE_API_KEY: 'AIzaSyCjrve8kc1jA4s5pnxThwX2mcabzZcWdto',
  GETSTREAM_TOKEN: 'GETSTREAM_TOKEN',
  USER_DETAILS: [''],
  STREAM_CHAT_KEY:'8h7d6k9ttcsh',
  SELECTED_SCHOOL: 'SELECTED_SCHOOL',
  SELECTED_SCHOOLID: 'SELECTED_SCHOOLID',
  MYSCHOOL: 'MYSCHOOL',
  FCM_TOKEN: 'FCM_TOKEN',
  SENDER_ID:'696736664653',
  EMAIL:'EMAIL',
  MUTE_NOTIFICATION: '00',
  ROX_KEY:'6075d8bef8ecb835d0096e6b',
  FIXED_ROUTE_NAME:'Home',
  REFERRAL_LINK:'www',
  HOUSING_LOGO:'logo'
};

export default CONSTANTS;
